"""Export the recorded pruning decisions, not simulated results, for the website.

Usage:
    python3 scripts/export_tsh_data.py --source-root /path/to/results/sho
    python3 scripts/export_tsh_data.py --source-root /path/to/results/sho --check

The three source traces are external to the website. Only candidate descriptions
and survivor IDs are exported. Training flags, local paths, and logs stay private.
"""

import argparse
import json
import shlex
from pathlib import Path


DATASETS = {"symbol_qa": "Symbol-QA", "llm_qa": "LLM-QA", "real_qa": "Real-QA"}
RUN = "full_0.5_0.5_0.5_top10"
BUDGETS = [10, 20, 50, 100]
COUNTS = [45, 23, 10, 10]


def describe(candidate, candidate_id):
    flags = shlex.split(candidate["flags"])
    parts = candidate["tag"].split("+")
    weight = "si" in parts or any(part.startswith("online_ewc") for part in parts)
    function = any(part.startswith("sd") for part in parts)
    data = any(part.startswith("replay_token") for part in parts)
    merge = "merge" in parts
    labels = []
    if weight:
        labels.append("SI" if "si" in parts else "Online EWC")
    if function:
        labels.append(f"Self-distillation, weight {flags[flags.index('--distill_alpha') + 1]}")
    if data:
        replay_weight = flags[flags.index("--replay_weight") + 1]
        temperature = flags[flags.index("--replay_gen_temperature") + 1]
        labels.append(f"Replay, weight {replay_weight}, temperature {temperature}")
    labels.append("Merged LoRA" if merge else "Shared LoRA")
    return {"id": candidate_id, "anchors": int(weight) + 2 * int(function) + 4 * int(data),
            "merge": merge, "label": " + ".join(labels)}


def export(source_root):
    traces = {key: json.loads((source_root / key / RUN / "trace.json").read_text())
              for key in DATASETS}
    candidates = traces["symbol_qa"]["candidates"]
    tags = [candidate["tag"] for candidate in candidates]
    assert len(tags) == len(set(tags)) == 90, "Expected 90 unique candidates"
    ids = {tag: index for index, tag in enumerate(tags)}
    payload = {"seeds": [41, 42, 43], "candidates": [describe(c, i) for i, c in enumerate(candidates)],
               "datasets": {}}
    assert len({(c["anchors"], c["merge"]) for c in payload["candidates"]}) == 16
    for key, trace in traces.items():
        assert trace["candidates"] == candidates, f"Candidate pool differs for {key}"
        events = trace["rung_events"]
        assert [event["budget"] for event in events] == BUDGETS
        previous = set(tags)
        stages = []
        for event, count in zip(events, COUNTS):
            survivors = set(event["survived"])
            assert not event["failed"], f"Unexpected failed run in {key}"
            assert survivors <= previous and len(survivors) == count
            ranking = event["ranking"]
            assert {row["tag"] for row in ranking} == previous
            assert len(ranking) == event["n_ran"] == len(previous)
            assert {row["tag"] for row in sorted(ranking, key=lambda row: row["rank"])[:count]} == survivors
            assert {row["tag"] for row in ranking if row["survived"]} == survivors
            assert set(event["eliminated"]) == previous - survivors
            if event["budget"] == 100:
                assert survivors == previous, "There is no extra cut after task 100"
            stages.append({"task": event["budget"], "survivors": sorted(ids[tag] for tag in survivors)})
            previous = survivors
        assert all(payload["candidates"][ids[tag]]["merge"] and payload["candidates"][ids[tag]]["anchors"] & 4
                   for tag in previous), "The displayed final-survivor finding must hold"
        payload["datasets"][key] = {"label": DATASETS[key], "stages": stages}
    return "// Generated by scripts/export_tsh_data.py from recorded three-seed TSH rankings.\n" + \
           "window.COMPOSE_CL_TSH = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true", help="Validate without changing the generated asset")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / "static/js/tsh-data.js"
    content = export(args.source_root)
    if args.check:
        assert target.read_text() == content, "TSH asset differs from the recorded traces"
        print("PASS: exported decisions match all three traces and all four task boundaries.")
    else:
        target.write_text(content)
        print("Exported 90 candidates and recorded survivors for all three datasets.")


if __name__ == "__main__":
    main()
